name: Update dev branch
on:
  push:
    branches:
      - master
jobs:
  update-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Check if dev branch is up-to-date
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git checkout -b dev origin/dev
          if $(git log --oneline dev ^master | wc -l) == 0
          then
            echo "Dev branch is ahead of master. Skipping update."
            exit 0
          fi
      - name: Push changes to dev branch
        run: |
          git merge master
          git push --force -u origin dev
    # steps:
    #   - name: Checkout master branch
    #     uses: actions/checkout@v2
    #     with:
    #       token: ${{ secrets.PERSONAL_TOKEN }}
    #   - name: Push changes to dev branch
    #     run: |
    #       git checkout -b dev
    #       git merge master
    #       git config --global user.email "karhoutam@qq.com"
    #       git config --global user.name "KarhouTam"
    #       git push --force -u origin dev
