name: Update dev branch
on:
  push:
    branches:
      - master
jobs:
  update-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Push changes to dev branch
        run: |
          git config --global user.email "karhoutam@qq.com"
          git config --global user.name "KarhouTam"
          git checkout -b dev
          if $(git log --oneline dev ^master | wc -l) == 0
          then
            echo "Dev branch is ahead of master. Skipping update."
            exit 0
          else
          git merge master
          git push --force -u origin dev
          fi
