name: Update dev branch
on:
  push:
    branches:
      - master
jobs:
  update-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Push changes to dev branch
        run: |
          git checkout -b dev
          git merge master
          git config --global user.email "karhoutam@qq.com"
          git config --global user.name "KarhouTam"
          git push --force -u origin dev
