name: Update dev branch
on:
  push:
    branches:
      - master
jobs:
  update-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Push changes to dev branch
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git checkout dev
          git merge master
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git push --force origin dev
