name: Update dev branch
on:
  push:
    branches:
      - master
jobs:
  update-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Check if dev is ahead of master
        run: |
          git config --global user.email "karhoutam@qq.com"
          git config --global user.name "KarhouTam"
          git checkout -b dev
          master_commit=$(git rev-parse master)
          dev_commit=$(git rev-parse dev)
          if [ "$master_commit" != "$dev_commit" ]; then
            echo "Dev is ahead of master. Skipping sync."
            exit 0
          fi
      - name: Sync dev with master
        run: |
          git merge master;
          git push -u origin dev
