name: Update dev branch
on:
  push:
    branches:
      - master
jobs:
  update-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Check if dev is ahead of master
        run: |
          git config --global user.email "karhoutam@qq.com"
          git config --global user.name "KarhouTam"
          git fetch
          git checkout -b dev
          diff=$(git log --oneline dev ^master | wc -l)
          if [ "$diff" != 0 ]; then
            echo "::set-output name=sync_required::false"
            else
              echo "::set-output name=sync_required::true"
            fi
      - name: Sync dev with master
        if: steps.sync-dev.outputs.sync_required == 'true'
        run: |
          git checkout -b dev
          git merge master
          git push origin dev
          
